name:                adventOfCode2023

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/adventOfCode2021#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- QuickCheck
- containers
- split
- pqueue
- unordered-containers
- hashable
- mtl
- regex-base
- regex-posix

library:
  source-dirs: src

executables:
  adventOfCode2023-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventOfCode2023

tests:
  adventOfCode2023-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventOfCode2023
